# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhVUnZ5aQgKYJepUJZJXrIDrhKs9vuzg
"""

# 1. Write the defination of tuple with a proper example.

# -> Tuple is a data type in python.It is used to store multiple values.Most importantly it is unchangeable and unorderd.
# Real time example of tuple would be - Roll no.,emp id.

# Write the code for implementing sub dictionary inside dictionary.

student = {  1: {"name": "sanchi","course":"diploma","branch":"computer","year":"second"},
         2: {"name":"kanchi","course":"diploma","branch":"civil","year":"third"}}

student[1]["name"]

student[2]["branch"]